project:
  type: website
  output-dir: docs

website:
  title: "rruiz-s.github.io"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: CV
      - href: posts/posts.qmd
        text: Blog

  
  sidebar:
    - title: "Mastering Shiny"
      style: "docked"
      contents:
       - posts/2025-08-shiny/index.qmd
       - posts/2025-08-shiny/getting_started.qmd
       - posts/2025-08-shiny/shiny_in_action.qmd
    
format:
  html:
    css: assets/stylesheets/custom.scss
    toc: true
filters:
  - shinylive