project:
  type: website

website:
  favicon: media/country-icon.png
  title: "Ricardo Ruiz Sánchez"
  navbar:
    text: "Environmental scientist and GIS specialist"
    background: primary
    search: true
    right:
      - href: about.qmd
        text: Home
      - href: posts.qmd
        text: Posts
      - href: Curriculum.qmd
        text: Curriculum
  page-footer:
    background: light
    left:
      - "Environmental Scientist specialised on GIS"
    right:
      - icon: envelope
        href: mailto:r.ruizsanchez@students.uu.nl
format:
  html:
    theme: [cosmo, ./css/custom.scss]
    mainfont: Joan
    css: styles.css
    toc: true