project:
  type: website

website:
  title: "Ricardo RS"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Curriculum.qmd
      - Thesis.qmd

format:
  html:
    theme: [cosmo, ./css/custom.scss]
    css: styles.css
    toc: true