---
title: "WFS into PostgreSQL: Lakes in Italy"
description: "Importing WFS into PostgreSQL"
author:
  - name: Ricardo Ruiz Sánchez
categories:
  - Import
  - PostGIS
  - Marta
---


```{r}
#| echo: false
#| message: false
#| output: false
#| eval: false
lapply(c("DBI","sf","RPostgreSQL","prqlr"),require, character.only = T )
con <- DBI::dbConnect(RPostgres::Postgres(),
                        host = 'localhost',
                        port = 25432,
                        dbname = 'gis',
                        user = "docker",
                        password = "docker")
nuts <-st_read(con, layer ="nuts")
```


## Problem

# Methodology
## Install ogr_fdw

The tool [ogr_fdw](https://github.com/robe2/pgsql-ogr-fdw)

```{sql}
#| eval: false
CREATE SERVER geoserver_ita
	FOREIGN DATA WRAPPER ogr_fdw
	OPTIONS (
		datasource 'WFS:http://www.ideandalucia.es/services/DERA_g11_patrimonio/wfs',
		format 'WFS' );
```

##  Create the table

Before filling with any data, PostgreSQL needed the columns names from the WFS and their data type. How do we know the name of the columns and their type if we don't know yet even the name of the table.
What does that WFS really contains? **ogrinfo knows** , type in your local terminal:

```{sql}
#| eval: false
ogrinfo WFS:"http://www.ideandalucia.es/services/DERA_g11_patrimonio/wfs" -summary
```

Focus on '1: ID.ACQUEFISICHE.SPECCHI.ACQUA' . This is the name of the only table this WFS has. Now that we know the name of the table, let's see the ogrinfo of that tables. 
There are 2 options:
a) Use "-so" to observe only the column names, otherwise it will read all the data, which in this case takes a while.

```{sql}
#| eval: false
ogrinfo -so WFS:"http://www.ideandalucia.es/services/DERA_g11_patrimonio/wfs" ID.ACQUEFISICHE.SPECCHI.ACQUA
```


Instead of typing everything, copy the content and ask ChatGPT "create a postgresql using the following information "<paste the summary from the code 1>".  *To use the data from the WFS, include SERVER and OPTION.*


```{sql}
#| connection: con

CREATE FOREIGN TABLE pgrouting_book.specchi_acqua_ita(
    fid BIGINT, -- Field for the unique identifier
    boundary GEOMETRY, -- Assumed to be a spatial data type, change as necessary
    gml_id VARCHAR(255), -- GML identifier
    nome VARCHAR(255), -- Name of the water body
    origine VARCHAR(255), -- Origin of the data
    descrizione_origine VARCHAR(255), -- Description of the origin
    nasp VARCHAR(255), -- Additional information
    natura_specchio_acqua VARCHAR(255) -- Nature of the water body
)
SERVER "geoserver_ita"
	OPTIONS (layer 'ID.ACQUEFISICHE.SPECCHI.ACQUA');
```

To validate the data, execute the following code that will return the column and the data type that they contain.

```{sql}
#| connection: con
#| eval: false
SELECT  column_name, data_type
FROM information_schema.columns
WHERE table_name = 'id_acquefisiche_specchi_acqua';
```

```{sql}
#| connection: con
WITH area AS (
  SELECT 
    fid,
    st_area(ST_CurveToLine(boundary)::geography)/10000 as area_hm2
  FROM 
    pgrouting_book.specchi_acqua_ita
)
SELECT 
  acqua_ita.*, 
  area.area_hm2
FROM 
  pgrouting_book.specchi_acqua_ita AS acqua_ita
JOIN 
  area ON acqua_ita.fid = area.fid 
WHERE 
  acqua_ita.natura_specchio_acqua IN ('Lago', 'Bacino artificiale')
  AND area.area_hm2 > 0.2 
LIMIT 5;
```


